name: ${COMPOSE_PROJECT_NAME:-guess-the-pix}

services:
  guess-the-pix:
    build: .
    image: guess-the-pix:1.0.1
    container_name: ${CONTAINER_NAME:-guess-the-pix}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./bot.py:/app/bot.py:ro
      - ./config.py:/app/config.py:ro
      - ./database.py:/app/database.py:ro
